# Generated by Django 6.0.1 on 2026-03-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo (JPG or PNG format recommended)', null=True, upload_to='profile_photos/'),
        ),
    ]
