# Generated by Django 6.0.1 on 2026-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Account Payable'), (2, 'Account Supervisor'), (3, 'Finance Manager'), (4, 'General Manager'), (5, 'Managing Director'), (99, 'System Admin')], help_text="User's role level in the approval chain", null=True),
        ),
    ]
