# Generated by Django 6.0.1 on 2026-01-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv_number', models.CharField(blank=True, help_text='Auto-generated PV number in format YYMM-NNNN', max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Financial Supervisor'), ('PENDING_L3', 'Pending Finance Manager'), ('PENDING_L4', 'Pending General Manager'), ('PENDING_L5', 'Pending Managing Director'), ('ON_REVISION', 'On Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payee_name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=50)),
                ('requires_md_approval', models.BooleanField(default=False, help_text='Set by GM: whether MD approval is required')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_pending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='voucher_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vouchers.paymentvoucher')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('program', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_applicable', models.BooleanField(default=False, help_text='If checked, 10% VAT will be added')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vouchers.department')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='vouchers.paymentvoucher')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['pv_number'], name='vouchers_pa_pv_numb_b16a51_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['status', 'current_approver'], name='vouchers_pa_status_184289_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentvoucher',
            index=models.Index(fields=['created_at'], name='vouchers_pa_created_f91ec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherlineitem',
            unique_together={('voucher', 'line_number')},
        ),
    ]
