# Generated by Django 6.0.1 on 2026-01-29 09:47

import django.db.models.deletion
import vouchers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Account Supervisor'), ('PENDING_L3', 'Pending Finance Manager'), ('PENDING_L4', 'Pending General Manager'), ('PENDING_L5', 'Pending Managing Director'), ('ON_REVISION', 'On Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherattachment',
            name='file',
            field=models.FileField(upload_to=vouchers.models.voucher_attachment_path),
        ),
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_number', models.CharField(blank=True, help_text='Auto-generated PF number in format YYMM-PF-NNNN', max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_L2', 'Pending Account Supervisor'), ('PENDING_L3', 'Pending Finance Manager'), ('PENDING_L4', 'Pending General Manager'), ('PENDING_L5', 'Pending Managing Director'), ('ON_REVISION', 'On Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payee_name', models.CharField(max_length=200)),
                ('payment_date', models.DateField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=50)),
                ('requires_md_approval', models.BooleanField(default=False, help_text='Set by GM: whether MD approval is required')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forms_created', to=settings.AUTH_USER_MODEL)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_pending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('program', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_applicable', models.BooleanField(default=False, help_text='If checked, 10% VAT will be added')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vouchers.department')),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='vouchers.paymentform')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='FormAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=vouchers.models.form_attachment_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='vouchers.paymentform')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentform',
            index=models.Index(fields=['pf_number'], name='vouchers_pa_pf_numb_855eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentform',
            index=models.Index(fields=['status', 'current_approver'], name='vouchers_pa_status_56c979_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentform',
            index=models.Index(fields=['created_at'], name='vouchers_pa_created_5cce26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formlineitem',
            unique_together={('payment_form', 'line_number')},
        ),
    ]
