# Generated by Django 6.0.1 on 2026-01-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_paymentvoucher_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentform',
            name='bank_name',
            field=models.CharField(choices=[('ABA Bank', 'ABA Bank'), ('ACLEDA Bank', 'ACLEDA Bank'), ('MAYBANK (CAMBODIA)PLC', 'MAYBANK (CAMBODIA)PLC'), ('HONG LEONG BANK', 'HONG LEONG BANK'), ('BANK_EMIRATES NBD', 'BANK_EMIRATES NBD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bank_name',
            field=models.CharField(choices=[('ABA Bank', 'ABA Bank'), ('ACLEDA Bank', 'ACLEDA Bank'), ('MAYBANK (CAMBODIA)PLC', 'MAYBANK (CAMBODIA)PLC'), ('HONG LEONG BANK', 'HONG LEONG BANK'), ('BANK_EMIRATES NBD', 'BANK_EMIRATES NBD')], max_length=100),
        ),
    ]
