# Generated by Django 6.0.1 on 2026-01-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_paymentform_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentform',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='paymentform',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='The account number', max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='paymentform',
            name='bank_address',
            field=models.CharField(blank=True, choices=[('ABA Bank', 'ABA Bank'), ('ACLEDA Bank', 'ACLEDA Bank'), ('MAYBANK (CAMBODIA)PLC', 'MAYBANK (CAMBODIA)PLC'), ('HONG LEONG BANK', 'HONG LEONG BANK'), ('EMIRATES NBD', 'EMIRATES NBD')], default='', help_text='The name of the bank (ABA, ACLEDA, etc.)', max_length=100, verbose_name='Bank Address'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', help_text='The account number', max_length=50, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='bank_address',
            field=models.CharField(blank=True, choices=[('ABA Bank', 'ABA Bank'), ('ACLEDA Bank', 'ACLEDA Bank'), ('MAYBANK (CAMBODIA)PLC', 'MAYBANK (CAMBODIA)PLC'), ('HONG LEONG BANK', 'HONG LEONG BANK'), ('EMIRATES NBD', 'EMIRATES NBD')], default='', help_text='The name of the bank (ABA, ACLEDA, etc.)', max_length=100, verbose_name='Bank Address'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text="The name on the bank account (account holder's name)", max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='payee_name',
            field=models.CharField(max_length=200, verbose_name='Payee Name'),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text="The name on the bank account (account holder's name)", max_length=200, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payee_name',
            field=models.CharField(max_length=200, verbose_name='Payee Name'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
    ]
