# Generated by Django 6.0.1 on 2026-02-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_remove_paymentform_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)')], default='USD', help_text='Currency for this line item', max_length=3),
        ),
        migrations.AddField(
            model_name='voucherlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)')], default='USD', help_text='Currency for this line item', max_length=3),
        ),
    ]
