# Generated by Django 6.0.1 on 2026-02-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_formlineitem_currency_voucherlineitem_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='e.g., Phat Phnom Penh Co.,Ltd', max_length=200, verbose_name='Company Name')),
                ('account_number', models.CharField(help_text='e.g., 002 232 482', max_length=50, verbose_name='Account Number')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)')], default='USD', max_length=3, verbose_name='Currency')),
                ('bank', models.CharField(choices=[('ABA Bank', 'ABA Bank'), ('ACLEDA Bank', 'ACLEDA Bank'), ('MAYBANK (CAMBODIA)PLC', 'MAYBANK (CAMBODIA)PLC'), ('HONG LEONG BANK', 'HONG LEONG BANK'), ('EMIRATES NBD', 'EMIRATES NBD')], help_text='The bank where this account is held', max_length=100, verbose_name='Bank')),
                ('is_active', models.BooleanField(default=True, help_text="Inactive accounts won't be shown in selection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['company_name', 'bank'],
                'unique_together': {('account_number', 'bank')},
            },
        ),
        migrations.AddField(
            model_name='paymentform',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, help_text='Select the company bank account for this transfer', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.companybankaccount', verbose_name='Transfer by Account'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='company_bank_account',
            field=models.ForeignKey(blank=True, help_text='Select the company bank account for this transfer', null=True, on_delete=django.db.models.deletion.PROTECT, to='vouchers.companybankaccount', verbose_name='Transfer by Account'),
        ),
    ]
