# Generated by Django 6.0.1 on 2026-02-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_companybankaccount_paymentform_company_bank_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Auto-generated batch number (BATCH-YYYYMMDD-NNN)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending MD Signature'), ('SIGNED', 'Signed by MD'), ('REJECTED', 'Rejected by MD')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_ip', models.GenericIPAddressField(blank=True, help_text='IP address when MD signed', null=True)),
                ('fm_notes', models.TextField(blank=True, verbose_name='Finance Manager Notes')),
                ('md_comments', models.TextField(blank=True, verbose_name='MD Comments')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_batches_created', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signature_batches_signed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature Batch',
                'verbose_name_plural': 'Signature Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchVoucherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='vouchers.paymentvoucher')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_items', to='vouchers.signaturebatch')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('batch', 'voucher')},
            },
        ),
        migrations.CreateModel(
            name='BatchFormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('payment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='vouchers.paymentform')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_items', to='vouchers.signaturebatch')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('batch', 'payment_form')},
            },
        ),
    ]
