# Generated by Django 6.0.1 on 2026-05-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_signaturebatch_batchvoucheritem_batchformitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='revision_return_level',
            field=models.IntegerField(blank=True, help_text='Role level of approver who returned for revision. Resubmission routes back to this level.', null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='revision_return_level',
            field=models.IntegerField(blank=True, help_text='Role level of approver who returned for revision. Resubmission routes back to this level.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentform',
            name='pf_number',
            field=models.CharField(blank=True, help_text='Auto-generated PF number in format YYMM-NNNN', max_length=20, null=True, unique=True),
        ),
    ]
