# Generated by Django 6.0.1 on 2026-05-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_add_revision_return_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)'), ('RMB', 'Chinese Yuan (¥)')], default='USD', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='formlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)'), ('RMB', 'Chinese Yuan (¥)')], default='USD', help_text='Currency for this line item', max_length=3),
        ),
        migrations.AlterField(
            model_name='voucherlineitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('KHR', 'Cambodian Riel (៛)'), ('THB', 'Thai Baht (฿)'), ('RMB', 'Chinese Yuan (¥)')], default='USD', help_text='Currency for this line item', max_length=3),
        ),
    ]
