# Generated by Django 6.0.1 on 2026-01-27 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes visible only to approvers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vouchers.paymentvoucher')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('RETURN', 'Returned for Revision')], max_length=20)),
                ('actor_role_level', models.IntegerField(help_text='Role level of actor at time of action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='approval_signatures/%Y/%m/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='vouchers.paymentvoucher')),
            ],
            options={
                'verbose_name_plural': 'Approval histories',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['voucher', 'timestamp'], name='workflow_ap_voucher_00aa39_idx')],
            },
        ),
    ]
