# Generated by Django 6.0.1 on 2026-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_formcomment_formapprovalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20)),
                ('database_type', models.CharField(choices=[('SQLITE', 'SQLite'), ('POSTGRESQL', 'PostgreSQL')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Backup duration in seconds', null=True)),
            ],
            options={
                'verbose_name_plural': 'Backup histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='workflow_ba_created_5996ca_idx'), models.Index(fields=['status'], name='workflow_ba_status_c694e8_idx')],
            },
        ),
    ]
