# Generated by Django 6.0.1 on 2026-02-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_backuphistory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backuphistory',
            name='workflow_ba_created_5996ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='backuphistory',
            name='workflow_ba_status_c694e8_idx',
        ),
        migrations.DeleteModel(
            name='BackupHistory',
        ),
    ]
